/**:
  ros__parameters:
    video_device: "/dev/video0"
    image_width: 1280
    image_height: 720
    pixel_format: "yuyv"
    framerate: 15.0
    camera_frame_id: "camera_link"
    io_method: "mmap"
    frame_id: "camera"
    camera_info_url: ""
    camera_name: "camera"
    brightness: 100